// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentium.Registry.Infrastructure.Data;

#nullable disable

namespace Sentium.Registry.Infrastructure.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    partial class RegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sentium.Registry.Core.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Sentium.Registry.Core.Entities.SystemSettings", b =>
                {
                    b.OwnsOne("Sentium.Registry.Core.Settings.SettingsContainer", "Settings", b1 =>
                        {
                            b1.Property<Guid>("SystemSettingsId");

                            b1.HasKey("SystemSettingsId");

                            b1.ToTable("SystemSettings");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("SystemSettingsId");

                            b1.OwnsOne("Sentium.Registry.Core.Settings.HarnessSettings", "Harness", b2 =>
                                {
                                    b2.Property<Guid>("SettingsContainerSystemSettingsId");

                                    b2.Property<bool>("IsBuiltInHarnessEnabled");

                                    b2.Property<string>("UserHarnessPrompt")
                                        .IsRequired();

                                    b2.HasKey("SettingsContainerSystemSettingsId");

                                    b2.ToTable("SystemSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("SettingsContainerSystemSettingsId");
                                });

                            b1.Navigation("Harness")
                                .IsRequired();
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
