minimumReleaseAge: 10080
blockExoticSubdeps: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600

overrides:
  vite-plugin-sass-dts>vite: "$vite"
  "minimatch@>=5>brace-expansion": ">=5.0.6"

allowBuilds:
  "@parcel/watcher": false
