using Sentium.AgentRuntime.Core.Agents;

namespace Sentium.AgentRuntime.Application.Agents.Native;

/// <summary>
/// A specialized native agent dedicated to information synthesis and condensation.
/// This agent is typically used at the end of a multi-agent workflow to transform
/// raw or complex findings into concise, highly readable summaries.
/// </summary>
public sealed class SummaryAgent : IAgent
{
    /// <inheritdoc />
    /// <value><see cref="AgentRole.Summarizer"/> ("Summarizer")</value>
    /// <remarks>Must equal the key this agent is registered under (<see cref="AgentRole.Summarizer"/>) so the planner
    /// can name it and the factory can resolve it back to this native agent.</remarks>
    public string Name => AgentRole.Summarizer;

    /// <inheritdoc />
    /// <remarks>
    /// This agent's primary objective is brevity and clarity. It focuses on extracting
    /// the key takeaways and core insights from large blocks of text or historical execution logs
    /// generated by upstream squad agents.
    /// </remarks>
    public string Instructions => @"You are an expert information synthesizer and technical communicator.

    Your core objective is brevity and clarity. Review the provided text, multi-agent discussion history, or execution logs, and transform them into a concise, well-structured, and easily digestible summary.

    Ensure you:
    1. Extract the primary outcomes, key takeaways, and core findings.
    2. Eliminate redundant token noise, conversational filler, and circular logic.
    3. Maintain absolute accuracy regarding technical facts, metrics, or decisions made by the squad.
    4. Keep it highly scannable using clear markdown bullet points where appropriate.";
}
