name: "🚀 Feature"
description: "New user-facing functionality"
title: "[Feature]: "
labels: ["feature"]
assignees:
  - Shredrox
body:
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature
    validations:
      required: true
