name: "📈 Improvement"
description: "Improve existing behavior"
title: "[Improve]: "
labels: ["improvement"]
assignees:
  - Shredrox
body:
  - type: textarea
    attributes:
      label: Proposed improvement
    validations:
      required: true
