using AgentRuntime.Core.Agents;

namespace AgentRuntime.Application.Agents.Native;

/// <summary>
/// A specialized native agent dedicated to information synthesis and condensation.
/// This agent is typically used at the end of a multi-agent workflow to transform
/// technical findings into concise, readable summaries.
/// </summary>
public sealed class SummaryAgent : IAgent
{
    /// <inheritdoc />
    /// <value>"Summary Agent"</value>
    public string Name => "Summary Agent";

    /// <inheritdoc />
    /// <remarks>
    /// This agent's primary objective is brevity and clarity. It focuses on extracting
    /// the key takeaways from large blocks of text, often generated by domain experts
    /// like the <see cref="SecurityAnalyst"/> or <see cref="ForensicsAgent"/>.
    /// </remarks>
    public string Instructions => "You are a helpful assistant that summarizes text concisely.";
}
