minimumReleaseAge: 10080
blockExoticSubdeps: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600

overrides:
  vite-plugin-sass-dts>vite: "$vite"
  eslint-plugin-react-hooks>@babel/core: "$@babel/core"

allowBuilds:
  "@parcel/watcher": false
