// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sentium.Sandbox.Infrastructure.Data;

#nullable disable

namespace Sentium.Sandbox.Infrastructure.Migrations
{
    [DbContext(typeof(SandboxDbContext))]
    [Migration("20260516190013_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sentium.Sandbox.Core.Models.ExecutionLogEntry", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ExitCode")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginalUserPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyDenialReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PolicyDenied")
                        .HasColumnType("bit");

                    b.Property<Guid>("SentinelAuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("TimedOut")
                        .HasColumnType("bit");

                    b.HasKey("JobId");

                    b.ToTable("ExecutionLogs", (string)null);
                });

            modelBuilder.Entity("Sentium.Sandbox.Core.Models.ExecutionLogEntry", b =>
                {
                    b.OwnsMany("Sentium.Sandbox.Core.Models.ArtifactRecord", "Artifacts", b1 =>
                        {
                            b1.Property<Guid>("ExecutionLogEntryJobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("BlobUri")
                                .IsRequired();

                            b1.Property<string>("FileName")
                                .IsRequired();

                            b1.Property<string>("MimeType")
                                .IsRequired();

                            b1.Property<long>("SizeBytes");

                            b1.HasKey("ExecutionLogEntryJobId", "__synthesizedOrdinal");

                            b1.ToTable("ExecutionLogs");

                            b1
                                .ToJson("Artifacts")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionLogEntryJobId");
                        });

                    b.OwnsMany("Sentium.Sandbox.Core.Models.SandboxFileContext", "FileContext", b1 =>
                        {
                            b1.Property<Guid>("ExecutionLogEntryJobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<string>("FileName")
                                .IsRequired();

                            b1.HasKey("ExecutionLogEntryJobId", "__synthesizedOrdinal");

                            b1.ToTable("ExecutionLogs");

                            b1
                                .ToJson("FileContext")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionLogEntryJobId");
                        });

                    b.Navigation("Artifacts");

                    b.Navigation("FileContext");
                });
#pragma warning restore 612, 618
        }
    }
}
